name: Build and Push

on:
  workflow_dispatch:
    inputs:
      source_directory:
        description: 'Provide esignet plugin utility'
        required: true
        default: 'sign-in-with-esignet or secure-biometric-interface-integrator or storybook-example'
        type: string
      destination_branch:
        description: 'Provide artifactory branch'
        required: true
        type: string

jobs:
  sign-in-with-esignet:
    if: "contains(github.event.inputs.source_directory, 'sign-in-with-esignet')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: npm Install
        run: |
          cd sign-in-with-esignet
          npm i
      - name: Build APK
        run: |
          cd sign-in-with-esignet
          npm run build
      - name: Zip dist directory
        run: |
          cd sign-in-with-esignet
          mv dist sign-in-with-esignet
          zip -r sign-in-with-esignet.zip sign-in-with-esignet/

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v2
        with:
          name: sign-in-with-esignet
          path: sign-in-with-esignet/sign-in-with-esignet.zip

      - name: Copy ZIP file to esignet-plugins directory
        run:  |
          mkdir -p esignet-plugins
          cp ./sign-in-with-esignet/sign-in-with-esignet.zip  esignet-plugins/

      - name: Pushes esignet-plugin folder
        uses: datalbry/copy_folder_to_another_repo_action@1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACTION_PAT }}
        with:
          source_folder: esignet-plugins
          destination_repo: mosip/artifactory-ref-impl
          destination_folder: artifacts/src/esignet-plugins/sign-in-with-esignet/
          destination_branch: ${{ github.event.inputs.destination_branch }}
          user_name: mosip

  secure-biometric-interface-integrator:
    if: "contains(github.event.inputs.source_directory, 'secure-biometric-interface-integrator')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: npm Install
        run: |
          cd secure-biometric-interface-integrator
          npm i
      - name: Build APK
        run: |
          cd secure-biometric-interface-integrator
          npm run build

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          package_path: './secure-biometric-interface-integrator'
          registry-url: 'https://registry.npmjs.org/'
      - name: Publish package
        run: cd secure-biometric-interface-integrator && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Zip dist directory
        run: |
          cd secure-biometric-interface-integrator
          mv dist secure-biometric-interface-integrator
          zip -r secure-biometric-interface-integrator.zip secure-biometric-interface-integrator/

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v2
        with:
          name: secure-biometric-interface-integrator
          path: secure-biometric-interface-integrator/secure-biometric-interface-integrator.zip

      - name: Copy ZIP file to esignet-plugins directory
        run: |
          mkdir -p esignet-plugins
          cp ./secure-biometric-interface-integrator/secure-biometric-interface-integrator.zip  esignet-plugins/

      - name: Pushes esignet-plugin folder
        uses: datalbry/copy_folder_to_another_repo_action@1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACTION_PAT }}
        with:
          source_folder: esignet-plugins
          destination_repo: mosip/artifactory-ref-impl
          destination_folder: artifacts/src/esignet-plugins/secure-biometric-interface-integrator/
          destination_branch: ${{ github.event.inputs.destination_branch }}
          user_name: mosip

  storybook-example:
    if: "contains(github.event.inputs.source_directory, 'storybook-example')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: npm Install secure-biometric-interface-integrator
        run: |
          cd secure-biometric-interface-integrator
          npm install
      
      - name: npm Install sign-in-with-esignet
        run: |
          cd sign-in-with-esignet
          npm install
      
      - name: npm Install and Build storybook-example
        run: |
          cd storybook-example
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUBS_TOKEN }}
          publish_dir: storybook-example/storybook-static

